name: Fly Review Apps
on:
  pull_request: 
    types: ["opened", "edited", "synchronize"]
# write a github job that deploys a NEW fly app using the Machines api on every pull request
jobs:
  create_review_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: ./fly-launch-pr.sh ${{ github.event.number }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}